#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [1]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

#1st method of creating Series using Pandas

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [2]:
## Create a Series from dictionary

#2nd Method of creating Series using Pandas

data={'a':1,'b':2,'c':3}   # The key will become index for the table
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [3]:
#3rd method of creating Series using Pandas

data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
## Dataframe - It is 2D Heterogenous and mutable tabular data structed with labelled axes(i.e, rows and Columns)

## create a Dataframe from a dictionary of list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [5]:
#Convertint the above Dataframe to array using Numpy
import numpy as np
arr=np.array(df)
print(arr)

[['Krish' 25 'Bangalore']
 ['John' 30 'New York']
 ['Jack' 45 'Florida']]

In [6]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [7]:
df=pd.read_csv('data.csv')
df.head(5) # for top records

         Date Category  Value   Product  Sales Region
0  01/01/2023        A   28.0  Product1  754.0   East
1  02/01/2023        B   39.0  Product3  110.0  North
2  03/01/2023        C   32.0  Product2  398.0   East
3  04/01/2023        B    8.0  Product1  522.0   East
4  05/01/2023        B   26.0  Product3  869.0  North

In [8]:
df.tail(5) #for bottom records

          Date Category  Value   Product  Sales Region
45  15/02/2023        B   99.0  Product2  599.0   West
46  16/02/2023        B    6.0  Product1  938.0  South
47  17/02/2023        B   69.0  Product3  143.0   West
48  18/02/2023        C   65.0  Product3  182.0  North
49  19/02/2023        C   11.0  Product3  708.0  North

In [9]:
### Accessing Data From Dataframe
df

          Date Category  Value   Product  Sales Region
0   01/01/2023        A   28.0  Product1  754.0   East
1   02/01/2023        B   39.0  Product3  110.0  North
2   03/01/2023        C   32.0  Product2  398.0   East
3   04/01/2023        B    8.0  Product1  522.0   East
4   05/01/2023        B   26.0  Product3  869.0  North
5   06/01/2023        B   54.0  Product3  192.0   West
6   07/01/2023        A   16.0  Product1  936.0   East
7   08/01/2023        C   89.0  Product1  488.0   West
8   09/01/2023        C   37.0  Product3  772.0   West
9   10/01/2023        A   22.0  Product2  834.0   West
10  11/01/2023        B    7.0  Product1  842.0  North
11  12/01/2023        B   60.0  Product2    NaN   West
12  13/01/2023        A   70.0  Product3  628.0  South
13  14/01/2023        A   69.0  Product1  423.0   East
14  15/01/2023        A   47.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   93.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   31.0  Product2  578.0   West
19  20/01/2023        A   59.0  Product1  736.0   East
20  21/01/2023        C   82.0  Product3  606.0  South
21  22/01/2023        C   37.0  Product2  992.0  South
22  23/01/2023        B   62.0  Product3  942.0  North
23  24/01/2023        C   92.0  Product2  342.0   West
24  25/01/2023        A   24.0  Product2  458.0   East
25  26/01/2023        C   95.0  Product1  584.0   West
26  27/01/2023        C   71.0  Product2  619.0  North
27  28/01/2023        C   56.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   51.0  Product2  737.0  South
30  31/01/2023        B   50.0  Product3  735.0   West
31  01/02/2023        A   17.0  Product2  189.0   West
32  02/02/2023        B   63.0  Product3  338.0  South
33  03/02/2023        C   27.0  Product3    NaN   East
34  04/02/2023        C   70.0  Product3  669.0   West
35  05/02/2023        B   60.0  Product2    NaN   West
36  06/02/2023        C   36.0  Product3  177.0   East
37  07/02/2023        C    2.0  Product1    NaN  North
38  08/02/2023        C   94.0  Product1  408.0  South
39  09/02/2023        A   62.0  Product1  155.0   West
40  10/02/2023        B   15.0  Product1  578.0   East
41  11/02/2023        C   97.0  Product1  256.0   East
42  12/02/2023        A   93.0  Product3  164.0   West
43  13/02/2023        A   43.0  Product3  949.0   East
44  14/02/2023        A   96.0  Product3  830.0   East
45  15/02/2023        B   99.0  Product2  599.0   West
46  16/02/2023        B    6.0  Product1  938.0  South
47  17/02/2023        B   69.0  Product3  143.0   West
48  18/02/2023        C   65.0  Product3  182.0  North
49  19/02/2023        C   11.0  Product3  708.0  North

In [10]:
single=df['Category']  #will give all the values present in Category column
print(single)
type(single)   # as only single column is selected so its type will become Series from Dataframe

0     A
1     B
2     C
3     B
4     B
5     B
6     A
7     C
8     C
9     A
10    B
11    B
12    A
13    A
14    A
15    C
16    C
17    C
18    A
19    A
20    C
21    C
22    B
23    C
24    A
25    C
26    C
27    C
28    B
29    C
30    B
31    A
32    B
33    C
34    C
35    B
36    C
37    C
38    C
39    A
40    B
41    C
42    A
43    A
44    A
45    B
46    B
47    B
48    C
49    C
Name: Category, dtype: object

pandas.core.series.Series

In [11]:
#selects rows and columns using labels (names)
df.loc[0]  # will represent the 0th row (loc- location , iloc- index location)

Date        01/01/2023
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [12]:
#selects rows and columns using index numbers (positions)
print(df.iloc[0])  #will represent 0th row
print(df.iloc[0][0]) #It will represent the element at the index having 0th row and 0th column
print(df.iloc[0][1]) #It will represent the element at the index having 0th row and 1st column

Date        01/01/2023
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object
01/01/2023
A

C:\Users\littl\AppData\Local\Temp\ipykernel_5664\3805455151.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][0]) #It will represent the element at the index having 0th row and 0th column
C:\Users\littl\AppData\Local\Temp\ipykernel_5664\3805455151.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[0][1]) #It will represent the element at the index having 0th row and 1st column

In [13]:
df

          Date Category  Value   Product  Sales Region
0   01/01/2023        A   28.0  Product1  754.0   East
1   02/01/2023        B   39.0  Product3  110.0  North
2   03/01/2023        C   32.0  Product2  398.0   East
3   04/01/2023        B    8.0  Product1  522.0   East
4   05/01/2023        B   26.0  Product3  869.0  North
5   06/01/2023        B   54.0  Product3  192.0   West
6   07/01/2023        A   16.0  Product1  936.0   East
7   08/01/2023        C   89.0  Product1  488.0   West
8   09/01/2023        C   37.0  Product3  772.0   West
9   10/01/2023        A   22.0  Product2  834.0   West
10  11/01/2023        B    7.0  Product1  842.0  North
11  12/01/2023        B   60.0  Product2    NaN   West
12  13/01/2023        A   70.0  Product3  628.0  South
13  14/01/2023        A   69.0  Product1  423.0   East
14  15/01/2023        A   47.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   93.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   31.0  Product2  578.0   West
19  20/01/2023        A   59.0  Product1  736.0   East
20  21/01/2023        C   82.0  Product3  606.0  South
21  22/01/2023        C   37.0  Product2  992.0  South
22  23/01/2023        B   62.0  Product3  942.0  North
23  24/01/2023        C   92.0  Product2  342.0   West
24  25/01/2023        A   24.0  Product2  458.0   East
25  26/01/2023        C   95.0  Product1  584.0   West
26  27/01/2023        C   71.0  Product2  619.0  North
27  28/01/2023        C   56.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   51.0  Product2  737.0  South
30  31/01/2023        B   50.0  Product3  735.0   West
31  01/02/2023        A   17.0  Product2  189.0   West
32  02/02/2023        B   63.0  Product3  338.0  South
33  03/02/2023        C   27.0  Product3    NaN   East
34  04/02/2023        C   70.0  Product3  669.0   West
35  05/02/2023        B   60.0  Product2    NaN   West
36  06/02/2023        C   36.0  Product3  177.0   East
37  07/02/2023        C    2.0  Product1    NaN  North
38  08/02/2023        C   94.0  Product1  408.0  South
39  09/02/2023        A   62.0  Product1  155.0   West
40  10/02/2023        B   15.0  Product1  578.0   East
41  11/02/2023        C   97.0  Product1  256.0   East
42  12/02/2023        A   93.0  Product3  164.0   West
43  13/02/2023        A   43.0  Product3  949.0   East
44  14/02/2023        A   96.0  Product3  830.0   East
45  15/02/2023        B   99.0  Product2  599.0   West
46  16/02/2023        B    6.0  Product1  938.0  South
47  17/02/2023        B   69.0  Product3  143.0   West
48  18/02/2023        C   65.0  Product3  182.0  North
49  19/02/2023        C   11.0  Product3  708.0  North

In [14]:
## Accessing a specified element
print(df['Product'])#To access any column directly we use its specified header
print(df.at[2,'Value']) #Will represent the value present at the 2nd index(i.e, at the specific row index of the column)

0     Product1
1     Product3
2     Product2
3     Product1
4     Product3
5     Product3
6     Product1
7     Product1
8     Product3
9     Product2
10    Product1
11    Product2
12    Product3
13    Product1
14    Product2
15    Product1
16    Product2
17    Product1
18    Product2
19    Product1
20    Product3
21    Product2
22    Product3
23    Product2
24    Product2
25    Product1
26    Product2
27    Product2
28    Product3
29    Product2
30    Product3
31    Product2
32    Product3
33    Product3
34    Product3
35    Product2
36    Product3
37    Product1
38    Product1
39    Product1
40    Product1
41    Product1
42    Product3
43    Product3
44    Product3
45    Product2
46    Product1
47    Product3
48    Product3
49    Product3
Name: Product, dtype: object
32.0

In [15]:
df.at[2,'Category'] #It will show us what is present in the 2nd row of category column

'C'

In [16]:
## Accessing a specified element using iat
df.iat[2,2] #Here we are giving both row index and column index

np.float64(32.0)

In [17]:
df

          Date Category  Value   Product  Sales Region
0   01/01/2023        A   28.0  Product1  754.0   East
1   02/01/2023        B   39.0  Product3  110.0  North
2   03/01/2023        C   32.0  Product2  398.0   East
3   04/01/2023        B    8.0  Product1  522.0   East
4   05/01/2023        B   26.0  Product3  869.0  North
5   06/01/2023        B   54.0  Product3  192.0   West
6   07/01/2023        A   16.0  Product1  936.0   East
7   08/01/2023        C   89.0  Product1  488.0   West
8   09/01/2023        C   37.0  Product3  772.0   West
9   10/01/2023        A   22.0  Product2  834.0   West
10  11/01/2023        B    7.0  Product1  842.0  North
11  12/01/2023        B   60.0  Product2    NaN   West
12  13/01/2023        A   70.0  Product3  628.0  South
13  14/01/2023        A   69.0  Product1  423.0   East
14  15/01/2023        A   47.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   93.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   31.0  Product2  578.0   West
19  20/01/2023        A   59.0  Product1  736.0   East
20  21/01/2023        C   82.0  Product3  606.0  South
21  22/01/2023        C   37.0  Product2  992.0  South
22  23/01/2023        B   62.0  Product3  942.0  North
23  24/01/2023        C   92.0  Product2  342.0   West
24  25/01/2023        A   24.0  Product2  458.0   East
25  26/01/2023        C   95.0  Product1  584.0   West
26  27/01/2023        C   71.0  Product2  619.0  North
27  28/01/2023        C   56.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   51.0  Product2  737.0  South
30  31/01/2023        B   50.0  Product3  735.0   West
31  01/02/2023        A   17.0  Product2  189.0   West
32  02/02/2023        B   63.0  Product3  338.0  South
33  03/02/2023        C   27.0  Product3    NaN   East
34  04/02/2023        C   70.0  Product3  669.0   West
35  05/02/2023        B   60.0  Product2    NaN   West
36  06/02/2023        C   36.0  Product3  177.0   East
37  07/02/2023        C    2.0  Product1    NaN  North
38  08/02/2023        C   94.0  Product1  408.0  South
39  09/02/2023        A   62.0  Product1  155.0   West
40  10/02/2023        B   15.0  Product1  578.0   East
41  11/02/2023        C   97.0  Product1  256.0   East
42  12/02/2023        A   93.0  Product3  164.0   West
43  13/02/2023        A   43.0  Product3  949.0   East
44  14/02/2023        A   96.0  Product3  830.0   East
45  15/02/2023        B   99.0  Product2  599.0   West
46  16/02/2023        B    6.0  Product1  938.0  South
47  17/02/2023        B   69.0  Product3  143.0   West
48  18/02/2023        C   65.0  Product3  182.0  North
49  19/02/2023        C   11.0  Product3  708.0  North

In [18]:
### Data MAnipulation with Dataframe
df

          Date Category  Value   Product  Sales Region
0   01/01/2023        A   28.0  Product1  754.0   East
1   02/01/2023        B   39.0  Product3  110.0  North
2   03/01/2023        C   32.0  Product2  398.0   East
3   04/01/2023        B    8.0  Product1  522.0   East
4   05/01/2023        B   26.0  Product3  869.0  North
5   06/01/2023        B   54.0  Product3  192.0   West
6   07/01/2023        A   16.0  Product1  936.0   East
7   08/01/2023        C   89.0  Product1  488.0   West
8   09/01/2023        C   37.0  Product3  772.0   West
9   10/01/2023        A   22.0  Product2  834.0   West
10  11/01/2023        B    7.0  Product1  842.0  North
11  12/01/2023        B   60.0  Product2    NaN   West
12  13/01/2023        A   70.0  Product3  628.0  South
13  14/01/2023        A   69.0  Product1  423.0   East
14  15/01/2023        A   47.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   93.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   31.0  Product2  578.0   West
19  20/01/2023        A   59.0  Product1  736.0   East
20  21/01/2023        C   82.0  Product3  606.0  South
21  22/01/2023        C   37.0  Product2  992.0  South
22  23/01/2023        B   62.0  Product3  942.0  North
23  24/01/2023        C   92.0  Product2  342.0   West
24  25/01/2023        A   24.0  Product2  458.0   East
25  26/01/2023        C   95.0  Product1  584.0   West
26  27/01/2023        C   71.0  Product2  619.0  North
27  28/01/2023        C   56.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   51.0  Product2  737.0  South
30  31/01/2023        B   50.0  Product3  735.0   West
31  01/02/2023        A   17.0  Product2  189.0   West
32  02/02/2023        B   63.0  Product3  338.0  South
33  03/02/2023        C   27.0  Product3    NaN   East
34  04/02/2023        C   70.0  Product3  669.0   West
35  05/02/2023        B   60.0  Product2    NaN   West
36  06/02/2023        C   36.0  Product3  177.0   East
37  07/02/2023        C    2.0  Product1    NaN  North
38  08/02/2023        C   94.0  Product1  408.0  South
39  09/02/2023        A   62.0  Product1  155.0   West
40  10/02/2023        B   15.0  Product1  578.0   East
41  11/02/2023        C   97.0  Product1  256.0   East
42  12/02/2023        A   93.0  Product3  164.0   West
43  13/02/2023        A   43.0  Product3  949.0   East
44  14/02/2023        A   96.0  Product3  830.0   East
45  15/02/2023        B   99.0  Product2  599.0   West
46  16/02/2023        B    6.0  Product1  938.0  South
47  17/02/2023        B   69.0  Product3  143.0   West
48  18/02/2023        C   65.0  Product3  182.0  North
49  19/02/2023        C   11.0  Product3  708.0  North

In [19]:
## Adding a column
df['Profit']=[50]*50 
df

          Date Category  Value   Product  Sales Region  Profit
0   01/01/2023        A   28.0  Product1  754.0   East      50
1   02/01/2023        B   39.0  Product3  110.0  North      50
2   03/01/2023        C   32.0  Product2  398.0   East      50
3   04/01/2023        B    8.0  Product1  522.0   East      50
4   05/01/2023        B   26.0  Product3  869.0  North      50
5   06/01/2023        B   54.0  Product3  192.0   West      50
6   07/01/2023        A   16.0  Product1  936.0   East      50
7   08/01/2023        C   89.0  Product1  488.0   West      50
8   09/01/2023        C   37.0  Product3  772.0   West      50
9   10/01/2023        A   22.0  Product2  834.0   West      50
10  11/01/2023        B    7.0  Product1  842.0  North      50
11  12/01/2023        B   60.0  Product2    NaN   West      50
12  13/01/2023        A   70.0  Product3  628.0  South      50
13  14/01/2023        A   69.0  Product1  423.0   East      50
14  15/01/2023        A   47.0  Product2  893.0   West      50
15  16/01/2023        C    NaN  Product1  895.0  North      50
16  17/01/2023        C   93.0  Product2  511.0  South      50
17  18/01/2023        C    NaN  Product1  108.0   West      50
18  19/01/2023        A   31.0  Product2  578.0   West      50
19  20/01/2023        A   59.0  Product1  736.0   East      50
20  21/01/2023        C   82.0  Product3  606.0  South      50
21  22/01/2023        C   37.0  Product2  992.0  South      50
22  23/01/2023        B   62.0  Product3  942.0  North      50
23  24/01/2023        C   92.0  Product2  342.0   West      50
24  25/01/2023        A   24.0  Product2  458.0   East      50
25  26/01/2023        C   95.0  Product1  584.0   West      50
26  27/01/2023        C   71.0  Product2  619.0  North      50
27  28/01/2023        C   56.0  Product2  224.0  North      50
28  29/01/2023        B    NaN  Product3  617.0  North      50
29  30/01/2023        C   51.0  Product2  737.0  South      50
30  31/01/2023        B   50.0  Product3  735.0   West      50
31  01/02/2023        A   17.0  Product2  189.0   West      50
32  02/02/2023        B   63.0  Product3  338.0  South      50
33  03/02/2023        C   27.0  Product3    NaN   East      50
34  04/02/2023        C   70.0  Product3  669.0   West      50
35  05/02/2023        B   60.0  Product2    NaN   West      50
36  06/02/2023        C   36.0  Product3  177.0   East      50
37  07/02/2023        C    2.0  Product1    NaN  North      50
38  08/02/2023        C   94.0  Product1  408.0  South      50
39  09/02/2023        A   62.0  Product1  155.0   West      50
40  10/02/2023        B   15.0  Product1  578.0   East      50
41  11/02/2023        C   97.0  Product1  256.0   East      50
42  12/02/2023        A   93.0  Product3  164.0   West      50
43  13/02/2023        A   43.0  Product3  949.0   East      50
44  14/02/2023        A   96.0  Product3  830.0   East      50
45  15/02/2023        B   99.0  Product2  599.0   West      50
46  16/02/2023        B    6.0  Product1  938.0  South      50
47  17/02/2023        B   69.0  Product3  143.0   West      50
48  18/02/2023        C   65.0  Product3  182.0  North      50
49  19/02/2023        C   11.0  Product3  708.0  North      50

In [20]:
## Remove a column
df.drop('Profit',axis=1,inplace=True) #By defaul axis is 0 (i.e, Row) and we want to delete Profit, which is a column so axis = 1
                                      #used Inplace = True , as .drop is temporary operation so made it permanent using this

In [21]:
df

          Date Category  Value   Product  Sales Region
0   01/01/2023        A   28.0  Product1  754.0   East
1   02/01/2023        B   39.0  Product3  110.0  North
2   03/01/2023        C   32.0  Product2  398.0   East
3   04/01/2023        B    8.0  Product1  522.0   East
4   05/01/2023        B   26.0  Product3  869.0  North
5   06/01/2023        B   54.0  Product3  192.0   West
6   07/01/2023        A   16.0  Product1  936.0   East
7   08/01/2023        C   89.0  Product1  488.0   West
8   09/01/2023        C   37.0  Product3  772.0   West
9   10/01/2023        A   22.0  Product2  834.0   West
10  11/01/2023        B    7.0  Product1  842.0  North
11  12/01/2023        B   60.0  Product2    NaN   West
12  13/01/2023        A   70.0  Product3  628.0  South
13  14/01/2023        A   69.0  Product1  423.0   East
14  15/01/2023        A   47.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   93.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   31.0  Product2  578.0   West
19  20/01/2023        A   59.0  Product1  736.0   East
20  21/01/2023        C   82.0  Product3  606.0  South
21  22/01/2023        C   37.0  Product2  992.0  South
22  23/01/2023        B   62.0  Product3  942.0  North
23  24/01/2023        C   92.0  Product2  342.0   West
24  25/01/2023        A   24.0  Product2  458.0   East
25  26/01/2023        C   95.0  Product1  584.0   West
26  27/01/2023        C   71.0  Product2  619.0  North
27  28/01/2023        C   56.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   51.0  Product2  737.0  South
30  31/01/2023        B   50.0  Product3  735.0   West
31  01/02/2023        A   17.0  Product2  189.0   West
32  02/02/2023        B   63.0  Product3  338.0  South
33  03/02/2023        C   27.0  Product3    NaN   East
34  04/02/2023        C   70.0  Product3  669.0   West
35  05/02/2023        B   60.0  Product2    NaN   West
36  06/02/2023        C   36.0  Product3  177.0   East
37  07/02/2023        C    2.0  Product1    NaN  North
38  08/02/2023        C   94.0  Product1  408.0  South
39  09/02/2023        A   62.0  Product1  155.0   West
40  10/02/2023        B   15.0  Product1  578.0   East
41  11/02/2023        C   97.0  Product1  256.0   East
42  12/02/2023        A   93.0  Product3  164.0   West
43  13/02/2023        A   43.0  Product3  949.0   East
44  14/02/2023        A   96.0  Product3  830.0   East
45  15/02/2023        B   99.0  Product2  599.0   West
46  16/02/2023        B    6.0  Product1  938.0  South
47  17/02/2023        B   69.0  Product3  143.0   West
48  18/02/2023        C   65.0  Product3  182.0  North
49  19/02/2023        C   11.0  Product3  708.0  North

In [23]:
## Adds 1 to each datapoints of the Value column
df['Value']=df['Value']+1
df

          Date Category  Value   Product  Sales Region
0   01/01/2023        A   30.0  Product1  754.0   East
1   02/01/2023        B   41.0  Product3  110.0  North
2   03/01/2023        C   34.0  Product2  398.0   East
3   04/01/2023        B   10.0  Product1  522.0   East
4   05/01/2023        B   28.0  Product3  869.0  North
5   06/01/2023        B   56.0  Product3  192.0   West
6   07/01/2023        A   18.0  Product1  936.0   East
7   08/01/2023        C   91.0  Product1  488.0   West
8   09/01/2023        C   39.0  Product3  772.0   West
9   10/01/2023        A   24.0  Product2  834.0   West
10  11/01/2023        B    9.0  Product1  842.0  North
11  12/01/2023        B   62.0  Product2    NaN   West
12  13/01/2023        A   72.0  Product3  628.0  South
13  14/01/2023        A   71.0  Product1  423.0   East
14  15/01/2023        A   49.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   95.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   33.0  Product2  578.0   West
19  20/01/2023        A   61.0  Product1  736.0   East
20  21/01/2023        C   84.0  Product3  606.0  South
21  22/01/2023        C   39.0  Product2  992.0  South
22  23/01/2023        B   64.0  Product3  942.0  North
23  24/01/2023        C   94.0  Product2  342.0   West
24  25/01/2023        A   26.0  Product2  458.0   East
25  26/01/2023        C   97.0  Product1  584.0   West
26  27/01/2023        C   73.0  Product2  619.0  North
27  28/01/2023        C   58.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   53.0  Product2  737.0  South
30  31/01/2023        B   52.0  Product3  735.0   West
31  01/02/2023        A   19.0  Product2  189.0   West
32  02/02/2023        B   65.0  Product3  338.0  South
33  03/02/2023        C   29.0  Product3    NaN   East
34  04/02/2023        C   72.0  Product3  669.0   West
35  05/02/2023        B   62.0  Product2    NaN   West
36  06/02/2023        C   38.0  Product3  177.0   East
37  07/02/2023        C    4.0  Product1    NaN  North
38  08/02/2023        C   96.0  Product1  408.0  South
39  09/02/2023        A   64.0  Product1  155.0   West
40  10/02/2023        B   17.0  Product1  578.0   East
41  11/02/2023        C   99.0  Product1  256.0   East
42  12/02/2023        A   95.0  Product3  164.0   West
43  13/02/2023        A   45.0  Product3  949.0   East
44  14/02/2023        A   98.0  Product3  830.0   East
45  15/02/2023        B  101.0  Product2  599.0   West
46  16/02/2023        B    8.0  Product1  938.0  South
47  17/02/2023        B   71.0  Product3  143.0   West
48  18/02/2023        C   67.0  Product3  182.0  North
49  19/02/2023        C   13.0  Product3  708.0  North

In [ ]:
df.drop(0,inplace=True)  #This will drop the the 0th row , if axis was defined = 1 , so would have dropped 0th column

In [25]:
df

          Date Category  Value   Product  Sales Region
1   02/01/2023        B   41.0  Product3  110.0  North
2   03/01/2023        C   34.0  Product2  398.0   East
3   04/01/2023        B   10.0  Product1  522.0   East
4   05/01/2023        B   28.0  Product3  869.0  North
5   06/01/2023        B   56.0  Product3  192.0   West
6   07/01/2023        A   18.0  Product1  936.0   East
7   08/01/2023        C   91.0  Product1  488.0   West
8   09/01/2023        C   39.0  Product3  772.0   West
9   10/01/2023        A   24.0  Product2  834.0   West
10  11/01/2023        B    9.0  Product1  842.0  North
11  12/01/2023        B   62.0  Product2    NaN   West
12  13/01/2023        A   72.0  Product3  628.0  South
13  14/01/2023        A   71.0  Product1  423.0   East
14  15/01/2023        A   49.0  Product2  893.0   West
15  16/01/2023        C    NaN  Product1  895.0  North
16  17/01/2023        C   95.0  Product2  511.0  South
17  18/01/2023        C    NaN  Product1  108.0   West
18  19/01/2023        A   33.0  Product2  578.0   West
19  20/01/2023        A   61.0  Product1  736.0   East
20  21/01/2023        C   84.0  Product3  606.0  South
21  22/01/2023        C   39.0  Product2  992.0  South
22  23/01/2023        B   64.0  Product3  942.0  North
23  24/01/2023        C   94.0  Product2  342.0   West
24  25/01/2023        A   26.0  Product2  458.0   East
25  26/01/2023        C   97.0  Product1  584.0   West
26  27/01/2023        C   73.0  Product2  619.0  North
27  28/01/2023        C   58.0  Product2  224.0  North
28  29/01/2023        B    NaN  Product3  617.0  North
29  30/01/2023        C   53.0  Product2  737.0  South
30  31/01/2023        B   52.0  Product3  735.0   West
31  01/02/2023        A   19.0  Product2  189.0   West
32  02/02/2023        B   65.0  Product3  338.0  South
33  03/02/2023        C   29.0  Product3    NaN   East
34  04/02/2023        C   72.0  Product3  669.0   West
35  05/02/2023        B   62.0  Product2    NaN   West
36  06/02/2023        C   38.0  Product3  177.0   East
37  07/02/2023        C    4.0  Product1    NaN  North
38  08/02/2023        C   96.0  Product1  408.0  South
39  09/02/2023        A   64.0  Product1  155.0   West
40  10/02/2023        B   17.0  Product1  578.0   East
41  11/02/2023        C   99.0  Product1  256.0   East
42  12/02/2023        A   95.0  Product3  164.0   West
43  13/02/2023        A   45.0  Product3  949.0   East
44  14/02/2023        A   98.0  Product3  830.0   East
45  15/02/2023        B  101.0  Product2  599.0   West
46  16/02/2023        B    8.0  Product1  938.0  South
47  17/02/2023        B   71.0  Product3  143.0   West
48  18/02/2023        C   67.0  Product3  182.0  North
49  19/02/2023        C   13.0  Product3  708.0  North

In [26]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  01/01/2023        A   28.0  Product1  754.0   East
1  02/01/2023        B   39.0  Product3  110.0  North
2  03/01/2023        C   32.0  Product2  398.0   East
3  04/01/2023        B    8.0  Product1  522.0   East
4  05/01/2023        B   26.0  Product3  869.0  North

In [27]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("\nStatistical summary:\n", df.describe())

Data types:
 Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

Statistical summary:
            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [28]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000