### Reading Data From Different Sources

In [ ]:
import pandas as pd
from io import StringIO
#Data in json format(i.e, key value pairs, similar to dictonary of python expect that it only accepts strings in double quotes"")
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
#we are converting json into string using StringIO and then into a dataframe
df=pd.read_json(StringIO(Data))

In [3]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [6]:
df.to_json()  # to convert dataframe back to json
# we have not given any parameters, so it will print index, value for each key value pairs

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [7]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [8]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [9]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [11]:
df.head()  # As we did header=None, so it will show default column names with 0-13

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [13]:
df.to_csv("wine.csv") # we converted the above dataframe back to csv file and stored in a new csv file named wine.csv

In [16]:
#we can also read data from html file
!pip install lxml

Requirement already satisfied: lxml in C:\Users\littl\anaconda3\Lib\site-packages (5.3.0)

In [17]:
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: html5lib in C:\Users\littl\anaconda3\Lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in C:\Users\littl\anaconda3\Lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in C:\Users\littl\anaconda3\Lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in C:\Users\littl\anaconda3\Lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in C:\Users\littl\anaconda3\Lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\littl\anaconda3\Lib\site-packages (from beautifulsoup4) (4.15.0)

In [18]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url) # we copied a website url, and then converted its html data into dataframe

In [ ]:
print(df)  # will get the entire table in the form of a list
df[0] #will give first element of the list(our entire table in form of a dataframe look)

[                                            Bank Name                City  \
0                   Metropolitan Capital Bank & Trust             Chicago
1                        The Santa Anna National Bank          Santa Anna
2                                Pulaski Savings Bank             Chicago
3                  The First National Bank of Lindsay             Lindsay
4               Republic First Bank dba Republic Bank        Philadelphia
5                                       Citizens Bank            Sac City
6                            Heartland Tri-State Bank             Elkhart
7                                 First Republic Bank       San Francisco
8                                      Signature Bank            New York
9                                 Silicon Valley Bank         Santa Clara
10                                  Almena State Bank              Almena
11                         First City Bank of Florida   Fort Walton Beach
12                               The First State Bank       Barboursville
13                                 Ericson State Bank             Ericson
14                   City National Bank of New Jersey              Newark
15                                      Resolute Bank              Maumee
16                              Louisa Community Bank              Louisa
17                               The Enloe State Bank              Cooper
18                Washington Federal Bank for Savings             Chicago
19    The Farmers and Merchants State Bank of Argonia             Argonia
20                                Fayette County Bank          Saint Elmo
21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
22                                     First NBC Bank         New Orleans
23                                      Proficio Bank  Cottonwood Heights
24                      Seaway Bank and Trust Company             Chicago

            State   Cert                Acquiring Institution  \
0        Illinois  57488              First Independence Bank
1           Texas   5520            Coleman County State Bank
2        Illinois  28611                      Millennium Bank
3        Oklahoma   4134               First Bank & Trust Co.
4    Pennsylvania  27332    Fulton Bank, National Association
5            Iowa   8758            Iowa Trust & Savings Bank
6          Kansas  25851               Dream First Bank, N.A.
7      California  59017            JPMorgan Chase Bank, N.A.
8        New York  57053                  Flagstar Bank, N.A.
9      California  24735  First–Citizens Bank & Trust Company
10         Kansas  15426                          Equity Bank
11        Florida  16748            United Fidelity Bank, fsb
12  West Virginia  14361                       MVB Bank, Inc.
13       Nebraska  18265           Farmers and Merchants Bank
14     New Jersey  21111                      Industrial Bank
15           Ohio  58317                   Buckeye State Bank
16       Kentucky  58112    Kentucky Farmers Bank Corporation
17          Texas  10716                   Legend Bank, N. A.
18       Illinois  30570                   Royal Savings Bank
19         Kansas  17719                          Conway Bank
20       Illinois   1802            United Fidelity Bank, fsb
21      Wisconsin  30003  First-Citizens Bank & Trust Company
22      Louisiana  58302                         Whitney Bank
23           Utah  35495                    Cache Valley Bank
24       Illinois  19328                  State Bank of Texas

         Closing Date  Fund  Sort ascending
0    January 30, 2026                 10550
1       June 27, 2025                 10549
2    January 17, 2025                 10548
3    October 18, 2024                 10547
4      April 26, 2024                 10546
5    November 3, 2023                 10545
6       July 28, 2023                 10544
7         May 1, 2023                 10543
8      March 12, 2023                 10540
9      March 10, 2023                 10539
10   October 23, 2020                 10538
11   October 16, 2020                 10537
12      April 3, 2020                 10536
13  February 14, 2020                 10535
14   November 1, 2019                 10534
15   October 25, 2019                 10533
16   October 25, 2019                 10532
17       May 31, 2019                 10531
18  December 15, 2017                 10530
19   October 13, 2017                 10529
20       May 26, 2017                 10528
21        May 5, 2017                 10527
22     April 28, 2017                 10526
23      March 3, 2017                 10525
24   January 27, 2017                 10524  ]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [32]:
# url="https://en.wikipedia.org/wiki/Mobile_country_code"
# pd.read_html(url,match="Country",header=0)[0]  #match=country, gives the keyword in a specific table in the url... it will load only that table with country present in it at any location of the table
#we are getting an error while running the above code, as wikkipidea blocks our request to access it.. as it thinks a real browser is not accesing it, rather a bot is accessing its webstie

# to bypass
import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

# Trick Wikipedia into thinking it's a real browser
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)

# Now pass the HTML content directly to read_html
df = pd.read_html(response.text, match="Country", header=0)[0]
print(df)
# df[0]

     Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB
1                    412                                Afghanistan       AF
2                    276                                    Albania       AL
3                    603                                    Algeria       DZ
4                    544  American Samoa (United States of America)       AS
..                   ...                                        ...      ...
247                  452                                    Vietnam       VN
248                  543                        W Wallis and Futuna       WF
249                  421                                    Y Yemen       YE
250                  645                                   Z Zambia       ZM
251                  648                                   Zimbabwe       ZW

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN
1          List of mobile network codes in Afghanistan                    NaN
2              List of mobile network codes in Albania                    NaN
3              List of mobile network codes in Algeria                    NaN
4       List of mobile network codes in American Samoa                    NaN
..                                                 ...                    ...
247        List of mobile network codes in the Vietnam                    NaN
248  List of mobile network codes in Wallis and Futuna                    NaN
249          List of mobile network codes in the Yemen                    NaN
250             List of mobile network codes in Zambia                    NaN
251           List of mobile network codes in Zimbabwe                    NaN

                      Remarks
0    MCC is not listed by ITU
1                         NaN
2                         NaN
3                         NaN
4                         NaN
..                        ...
247                       NaN
248                       NaN
249                       NaN
250                       NaN
251                       NaN

[252 rows x 6 columns]

C:\Users\littl\AppData\Local\Temp\ipykernel_24476\887441390.py:16: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text, match="Country", header=0)[0]

In [33]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\littl\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\littl\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)

In [38]:
df_excel=pd.read_excel('data.xlsx')
df_excel

     Name  Age
0  Adarsh   23
1   Krish   32
2    Jack   31

In [39]:
df_excel.to_pickle('df_excel')  #converting the above excel file into a pickle file

In [42]:
pd.read_pickle('df_excel')

     Name  Age
0  Adarsh   23
1   Krish   32
2    Jack   31

In [ ]:
pd.read_  # we can see that there are multiple options to read any file using pandas